finished issue 1, created generateTrack class
LHRIC/Track-Analysis pull request #4
Opened 2024-09-28 20:54 UTC by Tacocat0254

2024-09-28 20:57 UTC, Navya025 commented on generateTrack.py
> +        self.df = None
could we make df a more descriptive variable name?

2024-09-28 21:10 UTC, Navya025 commented
Couple of quick things
1. can we make variable names more descriptive
2. update README.md with how to run the code
3. add a requirements.txt and update README.md with how to install the imports in the requirements.txt
4. plantUML diagram in README.md 

Great job :)

2024-10-02 03:38 UTC, tm1287 requested changes

2024-10-02 03:38 UTC, tm1287 commented on __pycache__/generateTrack.cpython-310.pyc
nit: Could we include a .footnote so we don't end up tracking some of these compilation/binary artifacts?

gitignore.io is a great resource for generating template .gitignore files for various languages

2024-10-05 19:01 UTC, merged